import:
  - graphs/eeg_{{ DEVICE }}.yaml
  {% if BITALINO %}
  - graphs/ecg_bitalino.yaml
  {% endif %}
  - graphs/classification.yaml
  - graphs/metrics.yaml
  - graphs/record.yaml
  - graphs/debug.yaml
  {% if OSC_ENABLE == "true" %}
  - graphs/osc.yaml
  {% endif %}

graphs:

  - id: Broker
    nodes:
    - id: broker
      module: timeflux.nodes.zmq
      class: Broker

  - id: UI
    nodes:
    - id: app
      module: timeflux_ui.nodes.ui
      class: UI
      params:
        routes:
          app: gui
        settings:
          app:
            training:
              baseline:
                enable: {{ BASELINE_ENABLE }}
                duration: {{ BASELINE_DURATION }}
              motor:
                enable: {{ MOTOR_ENABLE }}
                blocks: {{ MOTOR_BLOCKS }}
                trials: {{ MOTOR_TRIALS }}
                duration:
                  prep: 5000
                  rest: 8000
                  display_on: 6000
                  display_off: 2000
                  pause_before: 3000
                  pause_after: 6000
                imagery:
                  - LEFT
                  - RIGHT
                {% if MOTOR_IMAGERY == "rotation" %}
                media:
                  - path: assets/media/rotation_left.mp4
                    width: 320
                    position: bottom-left
                  - path: assets/media/rotation_right.mp4
                    width: 320
                    position: bottom-right
                {% elif MOTOR_IMAGERY == "extension" %}
                media:
                  - path: assets/media/extension_left.mp4
                    width: 320
                    position: bottom-left
                  - path: assets/media/extension_right.mp4
                    width: 320
                    position: bottom-right
                {% elif MOTOR_IMAGERY == "flexion" %}
                media:
                  - path: assets/media/flexion_left.mp4
                    width: 320
                    position: bottom-left
                  - path: assets/media/flexion_right.mp4
                    width: 320
                    position: bottom-right
                {% elif MOTOR_IMAGERY == "generic" %}
                media:
                  - path: assets/media/arrow_left.png
                    width: 320
                    #position: left
                    position: center
                  - path: assets/media/arrow_right.png
                    width: 320
                    #position: right
                    position: center
                {% endif %}
              blink:
                enable: {{ BLINK_ENABLE }}
                trials: {{ BLINK_TRIALS }}
            grid:
              shape:
                ratio: "1:1"
    - id: sub
      module: timeflux.nodes.zmq
      class: Sub
      params:
        topics: [ model, metrics, filtered ]
    - id: pub
      module: timeflux.nodes.zmq
      class: Pub
      params:
        topic: events
    edges:
      - source: sub:filtered
        target: app:eeg
      - source: sub:model
        target: app:model
      - source: sub:metrics
        target: app:metrics
      - source: app:events
        target: pub
    rate: 10
